# Travis-CI configuration file for UCAPA
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
language: cpp

compiler:
  - gcc
  - clang
  
#branches:
# only:
# - master

before_install:
  - sudo apt-get update -qq

install:
  #- sudo apt-get install libavcodec-dev libavformat-dev libavutil-dev libswscale-dev
  - sudo apt-get install yasm libva-dev zlib1g-dev
  # We need cmake >= 2.8.9
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu quantal main restricted"
  - sudo apt-get update -qq
  - sudo apt-get install cmake

before_script:
  # Asio
  - wget "http://downloads.sourceforge.net/project/asio/asio/1.10.1%20%28Stable%29/asio-1.10.1.tar.bz2?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fasio%2Ffiles%2Fasio%2F1.10.1%2520%2528Stable%2529%2F&ts=1396120955&use_mirror=heanet" -O ./asio-1.10.1.tar.bz2
  - mkdir external
  - tar -xvf asio-1.10.1.tar.bz2 -C external/
  - mv external/asio-1.10.1 external/asio
  # FFmpeg
  - wget ffmpeg.org/releases/ffmpeg-2.2.tar.bz2 -O ffmpeg-2.2.tar.bz2
  - tar -xvf ffmpeg-2.2.tar.bz2 -C external/
  - cd external/ffmpeg-2.2/
  - ./configure --prefix=../ffmpeg --disable-programs --disable-doc
  - make -j6
  - make install
  - cd ../../

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make VERBOSE=1 -j 4
